iter13
Akmyrzza/go-musthave-shortener pull request #15
Opened 2023-12-14 04:14 UTC by Akmyrzza

2023-12-14 10:56 UTC, s-shpak requested changes

2023-12-14 10:56 UTC, s-shpak commented on internal/app/app.go
> +		log.Println(err)
Не стоит продолжать выполнение здесь

2023-12-14 10:56 UTC, s-shpak commented on internal/app/app.go
> +			return cerror.ErrInMemoryRepo
Ты потерял `err` здесь, эту ошибку надо обернуть

2023-12-14 10:56 UTC, s-shpak commented on internal/config/config.go
> +	pgxSource := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable", "localhost", 5432, "postgres", "mysecret", "postgresdb")
Ты не должен хардкодить пароль даже дефолтный. Я не вижу смысла добавлять `dsn` по-умолчанию

2023-12-14 10:56 UTC, s-shpak commented on internal/mocks/mock_repo.go
Как ты сгенерировал этот файл?

2023-12-14 10:56 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +func initTables(db *sql.DB, tableName string) error {
Инициализировать схему БД необходимо при помощи миграции, смотри 4-ый вебинар, чтобы понять как

2023-12-14 10:56 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
Контекст надо брать извне (должен передаваться первым аргументом)

2023-12-14 10:56 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +func (s *StoreDB) PingStore() error {
```suggestion
func (s *StoreDB) Ping() error {
```

2023-12-14 10:56 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +	for i, v := range urls {
Кажется, что для этого лучше использовать https://pkg.go.dev/github.com/jackc/pgx/v5#Batch

2023-12-14 10:56 UTC, s-shpak commented on internal/repository/repository.go
> +func NewRepo(filePath string) (service.Repository, error) {
Хотелось бы, чтобы хранилище, использующее БД, также создавалось бы здесь. То есть бизнес-лоика должна передавать внутрь конфигурацию и получать на выходе `service.Repository`, не зная какой именно тип хранилища был инициализирован.

2023-12-14 10:56 UTC, s-shpak commented on internal/repository/repository.go
> +		return "", fmt.Errorf("not found in base")
Лучше добавить, какой `id` не был найден

2023-12-14 10:56 UTC, s-shpak commented on internal/repository/repository.go
> +	return errors.New("no ping")
Не стоит возвращать ошибку здесь?

2023-12-14 10:56 UTC, s-shpak commented on internal/repository/repository.go
> +			return nil, cerror.ErrAlreadyExist
Лучше добавить в ошибку информацию о том, какой `ShortURL` уже существует

2023-12-14 10:56 UTC, s-shpak commented on internal/server/handler/handler.go
> +func (h *Handler) GetOriginalURL(ctx *gin.Context) {
Здесь контекст должен быть типа `context.Context`, т.к. на этом уровне мы не знаем, какой фреймворк для обработки пользовательских запросов используется

2023-12-14 10:56 UTC, s-shpak commented on internal/server/handler/handler.go
> +	err := h.Service.Ping()
Т.к. это нештатная ошибка, ее стоит залогировать

2023-12-14 10:56 UTC, s-shpak commented on internal/server/handler/handler.go
> +		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "creating id error"})
надо залогировать

2023-12-14 10:56 UTC, s-shpak commented on internal/server/handler/handler.go
> +			ctx.JSON(http.StatusInternalServerError, gin.H{"error": "creating id error"})
надо залогировать

2023-12-14 10:56 UTC, s-shpak commented on internal/service/service.go
> +func (s *ServiceURL) CreateShortURL(originalURL string) (string, bool, error) {
Зачем ты возвращаешь `bool` здесь ?

2023-12-19 05:01 UTC, Akmyrzza commented on internal/app/app.go
> +		log.Println(err)
+

2023-12-19 05:16 UTC, Akmyrzza commented on internal/app/app.go
> +			return cerror.ErrInMemoryRepo
+

2023-12-19 05:16 UTC, Akmyrzza commented on internal/config/config.go
> +	pgxSource := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable", "localhost", 5432, "postgres", "mysecret", "postgresdb")
+

2023-12-19 05:17 UTC, Akmyrzza commented on internal/repository/pgsql/pgsql.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
+

2023-12-19 05:17 UTC, Akmyrzza commented on internal/repository/pgsql/pgsql.go
> +func (s *StoreDB) PingStore() error {
+

2023-12-19 05:21 UTC, Akmyrzza commented on internal/repository/repository.go
> +func NewRepo(filePath string) (service.Repository, error) {
+

2023-12-19 05:23 UTC, Akmyrzza commented on internal/repository/repository.go
> +		return "", fmt.Errorf("not found in base")
+

2023-12-19 05:23 UTC, Akmyrzza commented on internal/repository/repository.go
> +	return errors.New("no ping")
+

2023-12-19 05:24 UTC, Akmyrzza commented on internal/repository/repository.go
> +			return nil, cerror.ErrAlreadyExist
+

2023-12-19 05:24 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +func (h *Handler) GetOriginalURL(ctx *gin.Context) {
+

2023-12-19 05:25 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +	err := h.Service.Ping()
+

2023-12-19 05:25 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "creating id error"})
+

2023-12-19 05:25 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +			ctx.JSON(http.StatusInternalServerError, gin.H{"error": "creating id error"})
+

2023-12-19 05:27 UTC, Akmyrzza commented on internal/service/service.go
> +func (s *ServiceURL) CreateShortURL(originalURL string) (string, bool, error) {
чтобы понимать конфликт или нет

2023-12-20 15:54 UTC, s-shpak commented on internal/app/app.go
> +		log.Println(err)
Это не сделано

2023-12-20 15:54 UTC, s-shpak commented on internal/mocks/mock_repo.go
Вопрос остается в силе: напиши, пожалуйста, как ты сгенерировал этот файл. Или ты написал его вручную ?

2023-12-20 15:54 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +func initTables(db *sql.DB, tableName string) error {
Это не сделано

2023-12-20 17:08 UTC, s-shpak commented on internal/server/handler/handler.go
> +func (h *Handler) GetOriginalURL(ctx *gin.Context) {
Это не сделано

2023-12-20 17:08 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +	for i, v := range urls {
Это не сделано

2023-12-20 17:09 UTC, s-shpak commented on internal/repository/repository.go
> +	return errors.New("no ping")
Не надо возвращать ошибку, просто сразу выходи из функции

2023-12-20 17:11 UTC, s-shpak commented on internal/server/handler/handler.go
> +		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "creating id error"})
Не сделано

2023-12-20 17:11 UTC, s-shpak commented on internal/server/handler/handler.go
> +			ctx.JSON(http.StatusInternalServerError, gin.H{"error": "creating id error"})
Не сделано

2023-12-20 17:12 UTC, s-shpak commented on internal/service/service.go
> +func (s *ServiceURL) CreateShortURL(originalURL string) (string, bool, error) {
Ты можешь понять это, проанализировав ошибку (ее тип)

2023-12-20 17:14 UTC, s-shpak requested changes

2023-12-20 17:14 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +	err := s.DB.QueryRow(query, originalURL, shortURL).Scan(&id)
`INSERT` выполняется при помощи `Exec`, а не `Query`

2023-12-20 17:14 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +		return "", fmt.Errorf("error: db query exec: %w", err)
А как понять, что ошибка случилась из-за того, что произошла коллизия на уровне `shortURL` ?

2023-12-21 03:36 UTC, Akmyrzza commented on internal/app/app.go
> +		log.Println(err)
вы мой код смотрите?
нету  там такого я не понимаю

2023-12-21 03:37 UTC, Akmyrzza commented on internal/mocks/mock_repo.go
mockgen вс6е по курсу

2023-12-21 05:04 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "creating id error"})
ну я же добавил
вы не мой код смотрите? или старый я не понимаю

2023-12-21 05:04 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +			ctx.JSON(http.StatusInternalServerError, gin.H{"error": "creating id error"})
тоже добавлял

2023-12-21 05:05 UTC, Akmyrzza commented on internal/repository/pgsql/pgsql.go
> +	err := s.DB.QueryRow(query, originalURL, shortURL).Scan(&id)
так мне же надо получать ответ и обрабатывать его

2023-12-21 05:07 UTC, Akmyrzza commented on internal/repository/pgsql/pgsql.go
> +		return "", fmt.Errorf("error: db query exec: %w", err)
не понял вопроса

2023-12-21 11:10 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +		return "", fmt.Errorf("error: db query exec: %w", err)
Ты вызываешь `CreateShortURL` из `func (s *ServiceURL) CreateShortURL`. Там ты проверяешь ошибку на `cerror.ErrAlreadyExist`. `CreateShortURL` не возвращает эту ошибку. Как понять, что создать запись не получилось, потому что такой `shortURL` уже есть ?

2023-12-21 12:23 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +func (h *Handler) GetOriginalURL(ctx *gin.Context) {
ну тогда мой роутер не работает, он не принимает context.Context

2023-12-22 16:26 UTC, s-shpak commented on internal/repository/pgsql/migrations/00001_init.down.sql
Этот файл должен быть пустым ?

2023-12-22 16:26 UTC, s-shpak commented on internal/server/handler/handler.go
> +func (h *Handler) GetOriginalURL(ctx *gin.Context) {
А что если ты будешь регистрировать хендлеры в `router.go` так:

```go
	router.POST("/", func(ctx *gin.Context) {
		h.CreateShortURL(ctx)
	})
```

При этом твои хендлеры будут принимать на вход `context.Context`

2023-12-22 16:28 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +		return "", fmt.Errorf("error: db query exec: %w", err)
То, как ты это сделал не работает. Тебе надо понять, что ошибка произошла из-за коллизии и обернуть внутри `CreateShortURL` ошибку `cerror.ErrAlreadyExist`, которая на это указывает.

2023-12-23 07:22 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +func (h *Handler) GetOriginalURL(ctx *gin.Context) {
получается мне теперь надо все хэндлеры переписывать?
почему раньше не сказали об этом

2023-12-23 07:29 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +func (h *Handler) GetOriginalURL(ctx *gin.Context) {
router.POST("/", func(ctx *gin.Context) {
		h.CreateShortURL(ctx)
	}) это работать не будет потому что в ctx нет req и response откуда их брать???, я так понимаю надо отдельно как то передавать в параметр

2023-12-23 07:30 UTC, Akmyrzza commented on internal/repository/pgsql/pgsql.go
> +	for i, v := range urls {
у меня в tx нету метода (функции) newBatch

2023-12-23 07:31 UTC, Akmyrzza commented on internal/repository/pgsql/pgsql.go
> +	for i, v := range urls {
скорее всего что что моя база через sql.open а не pgx.conn ?

2023-12-23 07:32 UTC, Akmyrzza commented on internal/repository/pgsql/pgsql.go
> +		return "", fmt.Errorf("error: db query exec: %w", err)
это работает я сам вручную проверял и тесты все прошли

2023-12-23 07:32 UTC, Akmyrzza commented on internal/repository/pgsql/migrations/00001_init.down.sql
нет я добавлю дроп

2023-12-23 07:54 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +func (h *Handler) GetOriginalURL(ctx *gin.Context) {
func(c *gin.Context) {
        h.CreateShortURL(c.Request.Context(), c.Writer, c.Request)
    } так надо делать?

2023-12-25 08:21 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +	for i, v := range urls {
Стоит использовать `pgxpool`

2023-12-25 21:05 UTC, s-shpak approved these changes

2023-12-25 21:05 UTC, s-shpak commented on internal/repository/pgsql/pgsql.go
> +	"github.com/jackc/pgx/v4"
Необходимо использовать версию "github.com/jackc/pgx/v5"

2023-12-25 21:05 UTC, s-shpak commented on internal/server/handler/handler.go
> +func (h *Handler) GetOriginalURL(ctx *gin.Context) {
Обсудили на 1-1, пришли к выводу, что здесь контекст можно оставить как `*gin.Context`, но определение интерфейса сервиса надо поменять на:

```go
type ServiceURL interface {
	CreateShortURL(ctx context.Context, originalURL string) (string, error)
	GetOriginalURL(ctx context.Context, shortURL string) (string, error)
	Ping(ctx context.Context) error
	CreateShortURLs(ctx context.Context, urls []model.ReqURL) ([]model.ReqURL, error)
}
```

2023-12-25 21:06 UTC, s-shpak approved these changes

2023-12-26 04:49 UTC, merged