iter9
Akmyrzza/go-musthave-shortener pull request #9
Opened 2023-11-22 13:10 UTC by Akmyrzza

2023-11-23 10:55 UTC, s-shpak requested changes

2023-11-23 10:55 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.Fatalf("error: initializing config: %d", err)
Оборачивать ошибки надо при помощи `%w`

```suggestion
		log.Fatalf("error: initializing config: %w", err)
```

2023-11-23 10:55 UTC, s-shpak commented on go.mod
Необходимо обновить при помощи `go mod tidy`

2023-11-23 10:55 UTC, s-shpak commented on internal/app/app.go
> +		log.Fatalf("error, runnnig http server: %d", err)
Фаталиться в глубине кода нельзя: надо прокидывать ошибку наверх и обрабатывать ее там

2023-11-23 10:55 UTC, s-shpak commented on internal/app/app.go
> +	newLogger := logger.InitLogger()
Не используй префикс `new` при именовании новых переменных

2023-11-23 10:55 UTC, s-shpak commented on internal/repository/interface.go
> +type Repository interface {
Интерфейс должен объявляться там, где он используется

2023-11-23 10:55 UTC, s-shpak commented on internal/repository/local/repository.go
> +		log.Fatalf("error: opening db file: %d", err)
Фаталиться в глубине кода нельзя

2023-11-23 10:55 UTC, s-shpak commented on internal/repository/local/repository.go
> +		maxRecord, _ = strconv.Atoi(tmpRecord.ID)
Необходимо проверять ошибки

2023-11-23 10:55 UTC, s-shpak commented on internal/repository/local/repository.go
> +		if err := newDecoder.Decode(&tmpRecord); err != nil {
Тут надо проверить, что ошибка действительно говорит о том, что ты дошел до конца файла

2023-11-23 10:55 UTC, s-shpak commented on internal/repository/local/repository.go
> +type LocalRepository struct {
in-memory реализация также должна оставаться в коде

2023-11-23 10:55 UTC, s-shpak commented on internal/repository/local/repository.go
> +type TmpStorage struct {
Это используется только в данном пакете, а, значит, не должно экспортироваться

2023-11-23 10:55 UTC, s-shpak commented on internal/repository/local/repository.go
> +	if s.file == nil {
Если это так, то это ошибка

2023-11-23 10:55 UTC, s-shpak commented on internal/server/handler/handler.go
> +	resultString := h.BaseURL + "/" + id
См. https://pkg.go.dev/net/url#JoinPath

2023-11-23 10:55 UTC, s-shpak commented on internal/server/router/router.go
> +	router.Use(middleware2.LoggingRequest(l), gin.Recovery())
Логгинг должен производиться перед компрессией

2023-11-23 10:55 UTC, s-shpak commented on internal/server/util/logger/logger.go
> +	defer logger.Sync()
Это не имеет никакого смысла, т.к. синхронизация произойдет перед выходом из этой функции, а не перед завершением программы, так что это надо поправить

2023-11-23 10:55 UTC, s-shpak commented on internal/service/interface.go
> +type Service interface {
См. комментарий выше

2023-11-23 10:55 UTC, s-shpak commented on internal/service/service.go
> +	id := ""
Эта переменная не нужна

2023-11-23 10:55 UTC, s-shpak commented on internal/service/service.go
> +		_, ok := s.Repository.GetURL(id)
Это некорректно: необходимо пытаться вставить новое значение в базу и, в зависимости от ошибки, понимать, что это было сделано успешно, или генерировать новое

2023-11-23 10:55 UTC, s-shpak commented on internal/service/service.go
> +func (s *ServiceURL) GetURL(id string) (string, bool) {
Этот метод, кажется, не нужен

2023-11-23 11:20 UTC, Akmyrzza commented on cmd/shortener/main.go
> +		log.Fatalf("error: initializing config: %d", err)
done

2023-11-23 11:22 UTC, Akmyrzza commented on go.mod
done

2023-11-23 11:24 UTC, Akmyrzza commented on internal/app/app.go
> +		log.Fatalf("error, runnnig http server: %d", err)
done

2023-11-23 11:26 UTC, Akmyrzza commented on internal/app/app.go
> +	newLogger := logger.InitLogger()
done

2023-11-23 11:31 UTC, Akmyrzza commented on internal/server/util/logger/logger.go
> +	defer logger.Sync()
done

2023-11-23 11:39 UTC, Akmyrzza commented on internal/service/service.go
> +	id := ""
done

2023-11-23 11:52 UTC, Akmyrzza commented on internal/service/service.go
> +func (s *ServiceURL) GetURL(id string) (string, bool) {
не понимаю как тогда сделать обращение в репозитории с хэндлера

2023-11-25 19:31 UTC, Akmyrzza commented on internal/repository/local/repository.go
> +		log.Fatalf("error: opening db file: %d", err)
done

2023-11-25 19:33 UTC, Akmyrzza commented on internal/repository/local/repository.go
> +		maxRecord, _ = strconv.Atoi(tmpRecord.ID)
done

2023-11-25 19:34 UTC, Akmyrzza commented on internal/repository/local/repository.go
> +type TmpStorage struct {
done

2023-11-25 19:35 UTC, Akmyrzza commented on internal/repository/local/repository.go
> +	if s.file == nil {
что именно?

2023-11-25 19:38 UTC, Akmyrzza commented on internal/server/handler/handler.go
> +	resultString := h.BaseURL + "/" + id
done

2023-11-25 19:39 UTC, Akmyrzza commented on internal/server/router/router.go
> +	router.Use(middleware2.LoggingRequest(l), gin.Recovery())
done

2023-11-25 19:50 UTC, Akmyrzza commented on internal/service/service.go
> +		_, ok := s.Repository.GetURL(id)
done

2023-11-27 23:23 UTC, s-shpak commented on internal/repository/repository.go
> +type Repository interface {
Репозиторий используется не здесь, а в пакете `service`, значит он должен быть объявлен там

2023-11-27 23:23 UTC, s-shpak commented on internal/repository/local/repository.go
> +		if err := newDecoder.Decode(&tmpRecord); err != nil {
Это не сделано

2023-11-27 23:23 UTC, s-shpak commented on internal/repository/local/repository.go
> +type LocalRepository struct {
Это не сделано

2023-11-27 23:23 UTC, s-shpak commented on internal/repository/local/repository.go
> +	if s.file == nil {
Если `file == nil`, то это нештатная ситуация, значит это ошибка, значит вернуть надо не `nil`, а какую-то ошибку

2023-11-27 23:23 UTC, s-shpak commented on internal/server/handler/handler.go
> +	resultString := h.BaseURL + "/" + id
Нет, не сделано

2023-11-27 23:23 UTC, s-shpak commented on internal/server/util/logger/logger.go
> +	defer logger.Sync()
Но при выходе из программы логгер надо синхронизировать

2023-11-27 23:23 UTC, s-shpak commented on internal/service/interface.go
> +type Service interface {
Интерфейс должен определяться там, где он используется

2023-11-27 23:26 UTC, s-shpak requested changes
См. новые и старые комментарии.

Также добавь в проект линтер, как описано здесь: https://github.com/s-shpak/praktikum-golangci-lint

Я советую тебе взять 1-1, т.к., кажется, нам есть, что обсудить

2023-11-27 23:26 UTC, s-shpak commented on internal/service/service.go
> +		found := s.Repository.CreateID(id, originalURL)
Лучше это сделать через проверку ошибки

2023-11-27 23:26 UTC, s-shpak commented on internal/service/service.go
> +func (s *ServiceURL) GetURL(id string) (string, bool) {
Да, согласен, лучше обернуть

2023-11-29 13:05 UTC, s-shpak commented on internal/repository/repository.go
> +			if err == io.EOF {
Лучше использовать `errors.Is`

2023-11-29 13:05 UTC, s-shpak commented on internal/repository/local/repository.go
> +type LocalRepository struct {
Необходимо оставить две реализации, файловая реализация должна использовать in-memory реализацию

2023-11-29 13:24 UTC, s-shpak requested changes
См. комментарии

2023-12-01 11:11 UTC, s-shpak requested changes

2023-12-01 11:11 UTC, s-shpak commented on internal/repository/repository.go
> +	local   *LocalRepository
Это не правильно: `in-memory store` не должен знать о существовании `file store`. Кроме того, необходимо иметь возможность работать без сохранения данных на диск.

`FileStore` должен включать в себя `InMemoryStore`, он должен вызывать его методы при сохранении и чтении данных. Данные долны сохраняться на диск после записи в `InMemoryStore`

2023-12-01 11:11 UTC, s-shpak commented on internal/service/service.go
> +			} else {
Этот `else` не нужен

2023-12-01 11:11 UTC, s-shpak commented on internal/service/service.go
> +				return ""
Ошибку надо возвращать

2023-12-01 11:11 UTC, s-shpak commented on internal/repository/repository.go
> +			} else {
Этот `else` не нужен

2023-12-01 11:11 UTC, s-shpak commented on internal/repository/repository.go
> +				return nil, cerror.ErrDecodeFile
Не вижу смысла определять этот тип ошибки. Кроме того, ты не должен терять оригинальную ошибку. Лучше обернуть ее при помощи `fmt.Errorf` и вернуть

2023-12-01 11:18 UTC, Akmyrzza commented on internal/repository/repository.go
> +	local   *LocalRepository
Как диск может вызвать функции ин мемори, если сначала запись в инмемори потом в диск вы просите, я не понял

2023-12-01 11:23 UTC, Akmyrzza commented on internal/repository/repository.go
> +	local   *LocalRepository
Тут по задаче ин мемори всегда будет участвовать, а файл стор может и не быть, соответственно я ставлю в инмемори ссылкк на файл, если файла нет зачем мне инициализировать пустой объект

2023-12-02 18:20 UTC, s-shpak requested changes

2023-12-02 18:20 UTC, s-shpak commented on internal/repository/repository.go
> +func NewRepo(filePath string) (*LocalRepository, error) {
Тебе надо иметь возможность инициализировать как `*LocalRepository` так и `*InMemory` репозитори, в зависимости от конфигурации. Легче всего это сделать, передавая в конструктор объект конфигурации, и если он содержит путь к файу возвращать `*LocalRepository`, а иначе `*InMemory`.

Т.к. в Go функция не может возвращать два разных типа, можно возвращать общий интерфейс

2023-12-02 18:20 UTC, s-shpak commented on internal/repository/repository.go
> +	InMemoryRepo *InMemory
Это поле не надо делать экспортируемым

2023-12-03 12:31 UTC, s-shpak requested changes

2023-12-03 12:31 UTC, s-shpak commented on internal/repository/repository.go
> +type InMemory struct {
Этот тип не должен быть экспортируемым. Некоторые другие типы из этого пакета тоже. Исправь это: в Go должно экспортироваться только то, что используется внешними пакетами

2023-12-03 12:31 UTC, s-shpak commented on internal/repository/repository.go
> +func NewRepo(filePath string) (service.Repository, error) {
Здесь нарушается принцип направленности зависимостей: `Store` не должен знать о типе `service.Repository`. Объяви этот интерфейс в данном пакете и возвращай его

2023-12-05 11:24 UTC, s-shpak approved these changes

2023-12-13 19:27 UTC, merged